# Generated by Django 5.2.7 on 2025-10-27 10:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('total_loans', models.PositiveIntegerField(default=0)),
                ('total_returns', models.PositiveIntegerField(default=0)),
                ('total_reservations', models.PositiveIntegerField(default=0)),
                ('total_fines_collected', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_overdue_books', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Daily stats',
            },
        ),
        migrations.CreateModel(
            name='BookActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('details', models.JSONField(default=dict)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='books.book')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Book activities',
            },
        ),
    ]
